version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/Berlin'
      WEBPASSWORD: 'anigorissa'
      SERVERIP: $SERVERIP
      # use DnsWatch.info for private dns
      DNS1: ${DNS1:-'1.1.1.1'}
      DNS2: ${DNS2:-'1.0.0.1'}
    # Volumes store your data between container upgrades
    volumes:
      - '~/.pihole-docker/etc-pihole/:/etc/pihole/'
      - '~/.pihole-docker/etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    restart: unless-stopped